### ISSUE TITLE
[Feature Request] file-path highlighting (depth/type/etc)

### ISSUE THREAD

**Issue by JacobTravers** [gustavo-hms/peneira#4]
It would be nice to add some high-lighters to file-paths so they are more easily parsed by humans. I was thinking we could probably achieve this with regexes: for depth we could work on concurrent `.*?/`'s and for different file-extensions `\.rs$` or `\.js$` etc.

**Comment by gustavo-hms** [comment]
Hi, @JacobTravers !

Sorry again for the late reply...

> we could avoid visibility issues by using rgba: for faces

That doesn't work as expected for the following reasons:
1. `peneira` refers to the bult-in faces of Kakoune (the faces we tweak when we are creating a new colorscheme, like `type`, `function`, `PrimarySelection`...); this way, it adapts automatically to any colorscheme the user chooses;
2. once defined, those faces can't be made transparent; that is, I can't tell Kakoune I want to highlight the path using `PrimarySelection` but with `aa` as the value for the alpha channel.

That said, I tested some configurations in different colorschemes and came to the conclusion the `type` face works reasonably well in most configurations.

Also, judging by your comments, it seems you'd like to color differently  the extensions (say, green for `.rs`, yellow for `.js`, and so on).  Well, that doesn't seem to improve usability, but adds lots of complexity to the code, so I decided to don't do that.

In the `highlight-names` branch, you can test the new code. Please, take a look at that and see if it satisfies you, giving me some feedback otherwise.

**Comment by gustavo-hms** [comment]
I'm still experimenting with highlighting and decided for a more subtle one. Please, check both version in this branch and tell me what you think about them.

**Comment by JacobTravers** [comment]
@gustavo-hms Sorry for taking so long to get around to this! It looks great, I think the subtle version is a good default that will work with other themes well, and we the user can override it in the kakrc in order to customize it like so:
```
set-face global PeneiraFileName rgb:5CBE97
```

**Comment by gustavo-hms** [comment]
Excelent! I'm goona merge it right now then.
