### ISSUE TITLE
[Feature Request] peneira-lines for cwd and not just the current buffer

### ISSUE THREAD

**Issue by JacobTravers** [gustavo-hms/peneira#5]
It would be nice to use peneira to search lines in the current project and not just the current file if possible.

**Comment by gustavo-hms** [comment]
Well, it can be done with something like `peneira 'lines: ' 'rg -n ." %{...}`, but it doesn't seem to be as useful as it can appear at a first glance, since it would probably be very slow.

I think a better idea would have to have an alternative to the built-in Kakoune's `grep` command. A basic version (without custom highlighting) is very simple to write:

```kak
define-command peneira-grep -params 1 %{
    peneira 'line: ' "rg -n %arg{1}" %{
        lua %arg{1} %{
            local file, line = arg[1]:match("([^:]+):(%d+):")
            kak.edit(file, line)
        }
    }
}
```

I'm using `ripgrep` here, but it's easy to adapt it to use a combination of `find` and `grep`.

Is it enough for you?

**Comment by JacobTravers** [comment]
Yeah this works great thank you!
